config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :conferences
  root 'conferences#index'
end

app/models/conference.rb
class Conference < ActiveRecord::Base
	geocoded_by :address
	after_validation :geocode

  validates :dateandtime, :presence => true, :allow_blank => false
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
  before_action :set_conference, only: [:show, :edit, :update, :destroy]

  # GET /conferences
  # GET /conferences.json
  def index
    @conferences = Conference.all
  end

  # GET /conferences/1
  # GET /conferences/1.json
  def show
    @locations = Gmaps4rails.build_markers(@conference) do |conference, marker|
      marker.lat conference.latitude
      marker.lng conference.longitude
      marker.title conference.name
    end
    @client ||= ::GooglePlaces::Client.new(ENV['GOOGLE_PLACES'])
    @restaurants ||= @client.spots(@conference.latitude, @conference.longitude, :types => ['restaurant', 'food'])
    @hotels ||= @client.spots(@conference.latitude, @conference.longitude, :types => ['lodging', 'rv_park', 'park'])
    @transportation ||= @client.spots(@conference.latitude, @conference.longitude, :types => ['subway_station', 'bus_station', 'car_rental', 'train_station', 'taxi_stand', 'travel_agency'])
    @funstuff ||= @client.spots(@conference.latitude, @conference.longitude, :types => ['amusement_park', 'library', 'liquor_store', 'book_store', 'bar', 'museum', 'casino', 'night_club', 'dentist'])
  end

  # GET /conferences/new
  def new
    @conference = Conference.new
  end

  # GET /conferences/1/edit
  def edit
  end

  # POST /conferences
  # POST /conferences.json
  def create
    @conference = Conference.new(conference_params)

    respond_to do |format|
      if @conference.save
        format.html { redirect_to @conference, notice: 'Conference was successfully created.' }
        format.json { render :show, status: :created, location: @conference }
      else
        format.html { render :new }
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conferences/1
  # PATCH/PUT /conferences/1.json
  def update
    respond_to do |format|
      if @conference.update(conference_params)
        format.html { redirect_to @conference, notice: 'Conference was successfully updated.' }
        format.json { render :show, status: :ok, location: @conference }
      else
        format.html { render :edit }
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conferences/1
  # DELETE /conferences/1.json
  def destroy
    @conference.destroy
    respond_to do |format|
      format.html { redirect_to conferences_url, notice: 'Conference was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conference
      @conference = Conference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conference_params
      params.require(:conference).permit(:name, :dateandtime, :description, :address, :longitude, :latitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conferences_helper.rb
module ConferencesHelper
end

app/views/conferences/_form.html.erb
<%= form_for(@conference) do |f| %>
  <% if @conference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conference.errors.count, "error") %> prohibited this conference from being saved:</h2>

      <ul>
      <% @conference.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">  
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => "form-control"  %>
  </div>

  <div class="form-group">
    <%= f.label :dateandtime, "Date and Time" %><br>
    <%= f.datetime_local_field :dateandtime, :class => "form-control"  %>
    <%#= f.time_zone_select :dateandtime, ActiveSupport::TimeZone.us_zones %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, :class => "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/conferences/edit.html.erb
<h1>Editing Conference</h1>

<%= render 'form' %>

<%= link_to 'Show', @conference, 'data-no-turbolink' => true %> |
<%= link_to 'Back', conferences_path %>

app/views/conferences/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-6"> 
    <p>Welcome to ConferenceCat, your one stop shop for amenities and activities surrounding tech conferences. Below you will find a curated list of upcoming conferences. Click the links to see a more detailed description of each, along with its location and time. On the included map, you'll be able to quickly spot nearby food and beverage spots, as well as hotel and travel options.</p>

    <p>Utilizing various API services, we are able to aggregate this information in one place, giving you a more broad view of what each area has to offer.</p>
  </div>
  <div class="col-md-6">
    <img src="http://i.imgur.com/sc23QbJ.jpg?1" class="pull-right">
  </div>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Date</th>
    </tr>
  </thead>

  <tbody>
    <% @conferences.each do |conference| %>
      <tr>
        <td><%= link_to conference.name, conference, 'data-no-turbolink' => true %></td>
        <td><%= conference.address %></td>
        <td><%= conference.dateandtime.strftime('%b %d %Y') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if signed_in? %>

<br>

<%= link_to 'New Conference', new_conference_path %>

<% end %>

app/views/conferences/new.html.erb
<h1>Add A Conference</h1>

<%= render 'form' %>

<%= link_to 'Back', conferences_path %>

app/views/conferences/show.html.erb
  <script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry,visualization" type="text/javascript"></script>
  <script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>

<p id="notice"><%= notice %></p>

<div class="row">
  <h2><%= @conference.name %></h2>
</div>
<hr>

<div class="row">
  <div class="col-md-4">

    <div class="panel-group" role="tablist">
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="collapseListGroupHeading1">
          <h4 class="panel-title">
            <a class="" role="button" data-toggle="collapse" href="#collapseListGroup1" aria-expanded="true" aria-controls="collapseListGroup1">Hotels<span class="glyphicon glyphicon-triangle-bottom pull-right hotels"></a>
          </h4>
        </div>
        <div id="collapseListGroup1" class="panel-collapse collapse" role="tabpanel" aria-labelledby="collapseListGroupHeading1" aria-expanded="true">
          <ul class="list-group" id="hotels"></ul>
        </div>
      </div>
    </div>


    <div class="panel-group" role="tablist">
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="collapseListGroupHeading2">
          <h4 class="panel-title">
            <a class="" role="button" data-toggle="collapse" href="#collapseListGroup2" aria-expanded="true" aria-controls="collapseListGroup2">Restaurants<span class="glyphicon glyphicon-triangle-bottom pull-right restaurants"></a>
          </h4>
        </div>
        <div id="collapseListGroup2" class="panel-collapse collapse" role="tabpanel" aria-labelledby="collapseListGroupHeading2" aria-expanded="true">
          <ul class="list-group" id="restaurants"></ul>
        </div>
      </div>
    </div>

    <div class="panel-group" role="tablist">
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="collapseListGroupHeading3">
          <h4 class="panel-title">
            <a class="" role="button" data-toggle="collapse" href="#collapseListGroup3" aria-expanded="true" aria-controls="collapseListGroup3">Transportation<span class="glyphicon glyphicon-triangle-bottom pull-right transportation"></a>
          </h4>
        </div>
        <div id="collapseListGroup3" class="panel-collapse collapse" role="tabpanel" aria-labelledby="collapseListGroupHeading3" aria-expanded="true">
          <ul class="list-group" id="transportation"></ul>
        </div>
      </div>
    </div>

    <div class="panel-group" role="tablist">
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="collapseListGroupHeading4">
          <h4 class="panel-title">
            <a class="" role="button" data-toggle="collapse" href="#collapseListGroup4" aria-expanded="true" aria-controls="collapseListGroup4">Fun Stuff<span class="glyphicon glyphicon-triangle-bottom pull-right funstuff"></a>
          </h4>
        </div>
        <div id="collapseListGroup4" class="panel-collapse collapse" role="tabpanel" aria-labelledby="collapseListGroupHeading4" aria-expanded="true">
          <ul class="list-group" id="funstuff"></ul>
        </div>
      </div>
    </div>
 
  </div>
  <div class="col-md-8"> 

    <div class="panel panel-default">
      <div class="panel-body"> 
        <div style='width: 100%;'>
          <div id="map" style='width: 100%; height: 400px;'></div>
        </div>
      </div>
    </div>
    <div id="DirectionStuff"></div>
  </div>
</div>

<hr>
<div class="row well description">
  <div class="col-md-6">
    <p><strong>Description</strong></p>
    <p><%= @conference.description %></p>
  </div>
  <div class="col-md-6">
    <p><strong>Date</strong>: <%= @conference.dateandtime.strftime('%d %b %Y') %></p>
    <p><strong>Location</strong>: <%= @conference.address %></p>
  </div>
</div>

<script type='text/javascript'>
  $(document).ready(function(){
    $("#collapseListGroup1").on('shown.bs.collapse', function(){
      turnOnMarkers(hotels_markers);
    }).on('hidden.bs.collapse', function(){
      turnOffMarkers(hotels_markers);
      directionsDisplay.setMap(null);
      directionsDisplay.setPanel(null);
    });
    $("#collapseListGroup2").on('shown.bs.collapse', function(){
      turnOnMarkers(restaurants_markers);
    }).on('hidden.bs.collapse', function(){
      turnOffMarkers(restaurants_markers);
      directionsDisplay.setMap(null);
      directionsDisplay.setPanel(null);
    });
    $("#collapseListGroup3").on('shown.bs.collapse', function(){
      turnOnMarkers(transportation_markers);
    }).on('hidden.bs.collapse', function(){
      turnOffMarkers(transportation_markers);
      directionsDisplay.setMap(null);
      directionsDisplay.setPanel(null);
    });
    $("#collapseListGroup4").on('shown.bs.collapse', function(){
      turnOnMarkers(funstuff_markers);
    }).on('hidden.bs.collapse', function(){
      turnOffMarkers(funstuff_markers);
      directionsDisplay.setMap(null);
      directionsDisplay.setPanel(null);
    });

    $('.hotels').append(" " + hotels_json.length);
    $('.restaurants').append(" " + restaurants_json.length);
    $('.transportation').append(" " + transportation_json.length);
    $('.funstuff').append(" " + funstuff_json.length);
  });

  window.onload = function() {turnOffAllMarkersButOrigin();};

  function turnOffAllMarkersButOrigin() {
    turnOffMarkers(hotels_markers);      
    turnOffMarkers(restaurants_markers);
    turnOffMarkers(transportation_markers);
    turnOffMarkers(funstuff_markers);
  };

  function turnOffMarkers(markers_local) {
    for(i=0; i < markers_local.length; i++) {
      markers_local[i].setMap(null);
    }
      handler.removeMarkers(markers_local);
  }


  function turnOnMarkers(markers_local) {
    for(i=0; i < markers_local.length; i++) {
      markers_local[i].setMap(handler.getMap());
    }
    handler.addMarkers(markers_local);
  }

  locations_json = <%=raw @locations.to_json %>;
  restaurants_json = <%=raw @restaurants.to_json %>;
  transportation_json = <%=raw @transportation.to_json %>;
  hotels_json = <%=raw @hotels.to_json %>;
  funstuff_json=<%=raw @funstuff.to_json %>;

  function calcRoute(selected_marker) {
    var origin = new google.maps.LatLng(locations_json[0].lat, locations_json[0].lng);
    var destination = selected_marker;
    var request = {
      origin:       origin,
      destination:  destination,
      travelMode:   google.maps.TravelMode.DRIVING
    };
    directionsService.route(request, function(response, status) {
      if(status == google.maps.DirectionsStatus.OK){
        directionsDisplay.setMap(handler.getMap());
        directionsDisplay.setPanel(document.getElementById("DirectionStuff"));
        directionsDisplay.setDirections(response);
      } else {
        window.alert('Directions failed due to ' + status + "," +origin +","+ destination);
      }
    });
  }
  weightedPoints = [{"month": 1, "street": "ASHVILLE AV", "year": 2013, "lat": "35.7390", "offense": "Larceny", "lng": "-78.7868", "day": 1},
{"month": 1, "street": "BUCK JONES RD", "year": 2013, "lat": "35.7641", "offense": "Simple Assault", "lng": "-78.7434", "day": 1},
{"month": 1, "street": "BUCK JONES RD", "year": 2013, "lat": "35.7641", "offense": "Larceny", "lng": "-78.7434", "day": 1},
{"month": 1, "street": "BUFFWOOD CT", "year": 2013, "lat": "35.7243", "offense": "Larceny", "lng": "-78.8058", "day": 1},
{"month": 1, "street": "CHAPEL HILL RD", "year": 2013, "lat": "35.7989", "offense": "Alcohol Offenses", "lng": "-78.7971", "day": 1},
{"month": 1, "street": "CHAPEL HILL RD", "year": 2013, "lat": "35.7989", "offense": "Alcohol Offenses", "lng": "-78.7971", "day": 1},
{"month": 1, "street": "CHAPEL HILL RD", "year": 2013, "lat": "35.7989", "offense": "Drugs", "lng": "-78.7971", "day": 1},
{"month": 1, "street": "CHAPEL HILL RD/NE MAYNARD RD", "year": 2013, "lat": "35.7952", "offense": "Alcohol Offenses", "lng": "-78.7634", "day": 1},
{"month": 1, "street": "DELTA CT", "year": 2013, "lat": "35.7931", "offense": "Simple Assault", "lng": "-78.7865", "day": 1},
{"month": 1, "street": "GRANDE HEIGHTS DR", "year": 2013, "lat": "35.8047", "offense": "Vandalism", "lng": "-78.7806", "day": 1},
{"month": 1, "street": "HARLON DR", "year": 2013, "lat": "35.7714", "offense": "Burglary", "lng": "-78.7444", "day": 1},
{"month": 1, "street": "HARRISON OAKS BLVD", "year": 2013, "lat": "35.8332", "offense": "Larceny", "lng": "-78.7712", "day": 1},
{"month": 1, "street": "HIGH HOUSE RD", "year": 2013, "lat": "35.7824", "offense": "Robbery", "lng": "-78.7969", "day": 1},
{"month": 1, "street": "HIGHSTONE RD", "year": 2013, "lat": "35.7888", "offense": "Fraud", "lng": "-78.8527", "day": 1},
{"month": 1, "street": "JAMISON WOODS LN", "year": 2013, "lat": "35.6703", "offense": "Larceny", "lng": "-78.7630", "day": 1},
{"month": 1, "street": "KILDAIRE FARM RD", "year": 2013, "lat": "35.7373", "offense": "Larceny", "lng": "-78.7822", "day": 1},
{"month": 1, "street": "LUXON PL", "year": 2013, "lat": "35.7780", "offense": "Motor Vehicle Theft", "lng": "-78.8224", "day": 1},
{"month": 1, "street": "MAYNARD CROSSING CT", "year": 2013, "lat": "35.7867", "offense": "Drugs", "lng": "-78.8106", "day": 1},
{"month": 1, "street": "NEW CASTLE CT", "year": 2013, "lat": "35.7812", "offense": "Simple Assault", "lng": "-78.7937", "day": 1},
{"month": 1, "street": "RICHMOND CT", "year": 2013, "lat": "35.7565", "offense": "Vandalism", "lng": "-78.7593", "day": 1},
{"month": 1, "street": "RICHMOND CT", "year": 2013, "lat": "35.7565", "offense": "Aggravated Assault", "lng": "-78.7593", "day": 1},
{"month": 1, "street": "SE MAYNARD RD/KILMAYNE DR", "year": 2013, "lat": "35.7696", "offense": "Alcohol Offenses", "lng": "-78.7781", "day": 1},
{"month": 1, "street": "SW CARY PKWY", "year": 2013, "lat": "35.7818", "offense": "Burglary", "lng": "-78.8380", "day": 1},
{"month": 1, "street": "W CHATHAM ST/OLD APEX RD", "year": 2013, "lat": "35.7712", "offense": "Alcohol Offenses", "lng": "-78.8074", "day": 1},
{"month": 1, "street": "WALNUT ST", "year": 2013, "lat": "35.7724", "offense": "Fraud", "lng": "-78.7637", "day": 1},
{"month": 1, "street": "WESTON PKWY", "year": 2013, "lat": "35.8295", "offense": "Burglary", "lng": "-78.7717", "day": 1},
{"month": 1, "street": "ABBOTT LN", "year": 2013, "lat": "35.7983", "offense": "Burglary", "lng": "-78.7710", "day": 2},
{"month": 1, "street": "BONNELL CT", "year": 2013, "lat": "35.7565", "offense": "Burglary", "lng": "-78.7944", "day": 2},
{"month": 1, "street": "CAMDEN YARDS WAY", "year": 2013, "lat": "35.8236", "offense": "Vandalism", "lng": "-78.9129", "day": 2}];
  heatmapData = [];

  for(var i in weightedPoints) {
    heatmapData.push(new google.maps.LatLng(weightedPoints[i].lat, weightedPoints[i].lng));
  }

  CRIME_CONFERENCE = 15;
  directionsDisplay = new google.maps.DirectionsRenderer;
  directionsService = new google.maps.DirectionsService;
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers (locations_json, { "opacity": 0.7 });
    hotels_markers = handler.addMarkers(hotels_json);
    restaurants_markers = handler.addMarkers(restaurants_json);
    transportation_markers = handler.addMarkers(transportation_json);
    funstuff_markers = handler.addMarkers(funstuff_json);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(12);
    var heatmap = new google.maps.visualization.HeatmapLayer({
      data: heatmapData,
      radius: 50,
      maxIntensity: 450
    });
    if(<%=raw @conference.id %> == CRIME_CONFERENCE) {
      heatmap.setMap(handler.getMap());
    }
    directionsDisplay.setOptions({suppressMarkers: true});

    _.each(locations_json, function(json, index){
      json.marker = markers[index];
    });
    _.each(hotels_json, function(json, index){
      json.marker = hotels_markers[index];
    });
    _.each(restaurants_json, function(json, index){
      json.marker = restaurants_markers[index];
    });
    _.each(transportation_json, function(json, index){
      json.marker = transportation_markers[index];
    });
    _.each(funstuff_json, function(json, index){
      json.marker = funstuff_markers[index];
    });
    createSidebar(restaurants_json, '#restaurants');
    createSidebar(transportation_json, '#transportation');
    createSidebar(hotels_json, '#hotels');
    createSidebar(funstuff_json, '#funstuff');

  });
  
  function createSidebarLi(json){
      return ("<li class='list-group-item'><a>" + json.name + "</a></li>");
  };
  function bindLiToMarker($li, marker){
    $li.on('click', function(){
      handler.getMap().setZoom(17);
      turnOffAllMarkersButOrigin();
      marker.setMap(handler.getMap());
      marker.panTo();
      calcRoute(handler.getMap().getCenter());
      google.maps.event.trigger(marker.getServiceObject(), 'click');
    })
  };

  function createSidebar(json_array, id){
    _.each(json_array, function(json){
      var $li = $( createSidebarLi(json) );
      $li.appendTo(id);
      bindLiToMarker($li, json.marker);
    });
  };
</script>

<% if signed_in? %>
<%= link_to 'Edit', edit_conference_path(@conference) %> |
<%= link_to 'Delete', conference_path(@conference), method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>
<%= link_to 'Back', conferences_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ConferenceCat</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <!-- Fixed navbar -->
  <nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "ConferenceCat", root_path, :class => "navbar-brand" %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <% if signed_in? %>
          <li><a>Hey, <%= current_user.email %></a></li>
          <li><%= link_to "Sign Out?", destroy_user_session_path, method: :delete  %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div>

  <hr>
  <footer class="footer">
  <div class="container">
    <p class="text-muted"><%= link_to "ConferenceCat", root_path %> <%= link_to "©", new_user_session_path %> 2015 <a href="https://github.com/fungalraincloud">FungalRaincloud</a> &amp; <a href="https://github.com/dydx">dydx</a>, part of <a href="http://railsrumble.com/entries/130-conferencecat">RailsRumble 2015</a><a href="http://railsrumble.com/entries/130-conferencecat"><img src="https://d4nnn7wspfa3h.cloudfront.net/rails-rumble-badge-2015-sm.png" class="pull-right"></a></p>
  </div>
  </footer>

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-1060804-21', 'auto');
    ga('send', 'pageview');

  </script>

</body>
</html>